plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/saskiabinder/Documents/Coding/portfolio/build"
publishOrigin = "ui"
command = "npm run build"
commandOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]